/* Auto-generated by Build Station for legacy CMHW device classes. */
package org.lineageos.hardware.util;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public final class FileUtils {
    private FileUtils() { }

    public static String readOneLine(String path) {
        try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
            return reader.readLine();
        } catch (IOException ignored) {
            return null;
        }
    }

    public static boolean writeLine(String path, String value) {
        try (FileWriter writer = new FileWriter(path)) {
            writer.write(value);
            writer.write(10);
            return true;
        } catch (IOException ignored) {
            return false;
        }
    }
}
